[package]
name = "unison"
version = "0.1.0"
edition = "2021"

[dependencies]
unison-backend = { path = "../unison-backend" }
unison-backend-wgpu = { path = "../unison-backend-wgpu" }


winit = "0.28.5"
raw-window-handle = "0.5.1"
thiserror = "1.0"
paste = "1.0.12"
